{
	"version": 1734439848,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/a-sheet0.png",
		"images/a-sheet1.png",
		"images/cam-sheet0.png",
		"images/hp-sheet0.png",
		"images/h2-sheet0.png",
		"images/fade-sheet0.png",
		"images/soul-sheet0.png",
		"images/soul-sheet1.png",
		"images/frame-sheet0.png",
		"images/frame2-sheet0.png",
		"images/bone-sheet0.png",
		"images/コスチューム-sheet0.png",
		"images/screenshot-sheet0.png",
		"images/longnots-sheet0.png",
		"images/bb-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/gamelogo-sheet0.png",
		"images/gamelogo-sheet1.png",
		"images/gamelogo-sheet2.png",
		"images/gamelogo-sheet3.png",
		"images/gamelogo-sheet4.png",
		"images/gamelogo-sheet5.png",
		"images/gamelogo-sheet6.png",
		"images/gamelogo-sheet7.png",
		"media/media_mus_zz_megalovania.ogg",
		"media/y2mate.com-undertale-sound-effect-soul-damaged.ogg",
		"media/おとげーこうかおん.ogg",
		"media/unity.ogg",
		"media/ブルーアーカイブ blue archive ost 59. re aoharu [tuberipper.cc].ogg",
		"media/ブルアカ4th-pv-_mp3cut.net_-_mp3cut.net_-.ogg",
		"media/bruno mars - runaway baby (official lyric video) [tuberipper.cc].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}